### ISSUE TITLE
free_bike_status.available_until datetime regex too restrictive

### ISSUE THREAD

**Issue by hbruch** [MobilityData/gbfs-json-schema#95]
The [current datetime regex](https://github.com/MobilityData/gbfs-json-schema/blob/v3.1.2/v2.3/free_bike_status.json#L123) for `free_bike_status.available_until` does neither support numeric offsets, nor milliseconds (not that this precision would be required but...).

As https://github.com/MobilityData/gbfs/pull/522 plans to introduce RFC3339 as timestamp format, the regex will surely be revised, but even now, I suggest to expand it to this [stack overflow suggestion](https://stackoverflow.com/questions/3143070/regex-to-match-an-iso-8601-datetime-string#3143231) by Brock Adams:

```
(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))
```

**Comment by richfab** [comment]
Hello @hbruch,

I'm sorry for the delay. Thank you very much for this contribution! We all understand the importance of having an accurate JSON Schema.

Based on the current GBFS [spec](https://github.com/MobilityData/gbfs/blob/v2.3/gbfs.md#field-types) definition (v2.3):
>Datetime (added in v2.3)- Combination of a date and a time following [ISO 8601 notation](https://www.iso.org/iso-8601-date-and-time-format.html). Attributes : [year](https://docs.python.org/3/library/datetime.html#datetime.datetime.year), [month](https://docs.python.org/3/library/datetime.html#datetime.datetime.month), [day](https://docs.python.org/3/library/datetime.html#datetime.datetime.day), [hour](https://docs.python.org/3/library/datetime.html#datetime.datetime.hour), [minute](https://docs.python.org/3/library/datetime.html#datetime.datetime.minute), [second](https://docs.python.org/3/library/datetime.html#datetime.datetime.second), and timezone.
- I agree that the JSON-Schema should allow for the timezone to be included in `free_bike_status.available_until`. 
- I would recommend to not allow the milliseconds, to match the spec definition and because this level of precision is most likely not needed.

Please let me know:
1. If you agree with these changes.
2. If you would like to write the Pull Request, or if you would prefer that I take care of it.

Thank you!
Fabien

**Comment by richfab** [comment]
Hi @hbruch,
Just to let you know that we have updated the JSON Schemas (v2.3 and v3.0-RC) to allow timezones.
Thank you for your contribution.
Have a great!
